version: '3'
services:
  mongodb:
    image: mongo:latest  # Используется официальный образ MongoDB из Docker Hub
    ports:
      - "27017:27017"  # Можно настроить порты по вашему усмотрению
    volumes:
      - ./data/db:/data/db  # Монтируем том для хранения данных MongoDB
  webapp:
    build:
      context: . # Относительный путь к папке с вашим приложением
    ports:
      - "8080:8080"  # Замените на порт, который использует ваше приложение
    depends_on:
      - mongodb
